# Generated by Django 3.1.5 on 2021-02-22 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210219_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutors_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='contact',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='day_availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
