# Generated by Django 3.1.5 on 2021-02-22 05:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210222_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='day_availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, size=None),
        ),
    ]
