# Generated by Django 3.1.5 on 2021-02-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210227_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(default='Gender', max_length=10),
        ),
    ]
