# Generated by Django 3.1.5 on 2021-02-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210227_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(default='Phone Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='contact',
            field=models.CharField(default='Phone Number', max_length=20),
        ),
    ]
