# Generated by Django 3.1.5 on 2021-03-06 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210227_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='day_availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=[], size=None),
        ),
    ]
