# Generated by Django 3.1.5 on 2021-03-06 21:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210307_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='day_availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, size=None),
        ),
    ]
