# Generated by Django 3.1.5 on 2021-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210307_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='expertise',
            field=models.TextField(default='Enter your skill to highlight yourself', max_length=2000),
        ),
    ]
