# Generated by Django 3.1.5 on 2021-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tutor_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('t_id', models.IntegerField()),
                ('apmnt_time', models.DateField()),
                ('subject', models.CharField(max_length=1000)),
                ('duration', models.FloatField()),
                ('amount', models.FloatField()),
                ('message', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('accept', 'accept'), ('pending', 'pending'), ('reject', 'reject')], default='pending', max_length=10)),
            ],
        ),
    ]
