# Generated by Django 3.1.5 on 2021-03-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('s_id', models.IntegerField()),
                ('t_id', models.IntegerField()),
                ('s_status', models.CharField(choices=[('active', 'active'), ('done', 'done'), ('cancel', 'cancel')], default='active', max_length=10)),
                ('t_status', models.CharField(choices=[('active', 'active'), ('done', 'done'), ('cancel', 'cancel')], default='active', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending'), ('cancel', 'cancel')], default='pending', max_length=10),
        ),
    ]
