# Generated by Django 3.1.5 on 2021-03-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210314_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='m_id',
            new_name='meeting',
        ),
    ]
