# Generated by Django 3.1.5 on 2021-04-07 20:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210323_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=10)),
                ('card_number', models.IntegerField()),
                ('amount', models.FloatField(default=0.0)),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
        ),
    ]
