# Generated by Django 3.1.5 on 2021-04-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='card_number',
        ),
    ]
